### ISSUE TITLE
SocketXP - Remote Access fails to start correctly

### ISSUE THREAD

**Issue by dpeluso** [socketxp-com/home-assistant#1]
When trying to use the SocketXP home assistant add-on with the following configuration (_authtoken redacted_) I get the following error "/socketxp exited 255" in the log.

**-- Addon Configuration --**
authtoken: >-
            _...redacted..._
tunnel_enabled: true
tunnels:
  - destination: 'https://127.0.0.1:8123'
    protocol: tls
    custom_domain: ''
relay_enabled: false
relays:
  - destination: 'https://127.0.0.1:8123'

**-- Logs --**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Using config file: /data/options.json
Downloading and updating socketxp to the latest version!
SocketXP Agent upgrade completed!
Please rerun the socketxp command now.

[cmd] /socketxp exited 255
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by tech-freak** [comment]
facing same issue

**Comment by xerox1821** [comment]
same issue here

**Comment by gimadrislamov** [comment]
same issue

**Comment by LucasBednarek** [comment]
Exactly the same issue. @socketxp-com may you provide some technical information on how to debug the issue?

**Comment by socketxp-com** [comment]
Dear SocketXP Hassio Add-on users,
The issue has been addressed in 1.0.2 version
